[package]
categories = ["text-processing"]
description = "A library for runtime formatting in Rust"
edition = "2024"
keywords = ["runtime", "formatting", "string", "format", "derive"]
license = "MIT OR Apache-2.0"
name = "rtformat"
readme = "README.md"
repository = "https://github.com/YWZYXSoCool/rtformat"
version = "0.1.2"

[dependencies]
rtformat-derive = {path = "rtformat-derive", version = "0.1.1"}

[workspace]
members = ["rtformat-derive"]
