[package]
categories = ["text-processing"]
description = "A library for runtime formatting in Rust"
edition = "2024"
keywords = ["runtime", "formatting", "string", "format", "derive"]
license = "MIT OR Apache-2.0"
name = "rtformat"
readme = "README.md"
repository = "https://github.com/YWZYXSoCool/rtformat"
rust-version = "1.88"
version = "0.1.4"

[dependencies]
rtformat-derive = {path = "rtformat-derive", version = "0.1.1"}

[dev-dependencies]
criterion = "0.8.2"

[[bench]]
harness = false
name = "format"

[workspace]
members = ["rtformat-derive"]
